#! /bin/bash -

copy_path=${3}
copy_path=${copy_path:-"/folk/jhu2/vlm/"}

nb()
{
    search_val=$1
    for target_id in `/folk/vlm/commandline/vlmTool find  -s amazon.wrs.com -l all | grep "$search_val" -B34|grep "^Target ID" |awk -F": " '{print $2}'`
    do
        target_info=`/folk/vlm/commandline/vlmTool getAttr -s amazon.wrs.com -t $target_id all | grep $search_val`
        target_reserved=`/folk/vlm/commandline/vlmTool getAttr -s amazon.wrs.com -t $target_id all | grep "^Reserved By"` 
        if [ -n "$target_info" ];then
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>"
            echo $target_id
            if [ "$target_info" != "$target_reserved" ];then
                echo $target_info
                echo $target_reserved
            else
                echo $target_info
            fi
            echo "<<<<<<<<<<<<<<<<<<<<<<<<<"
        fi
    done
}

nb1()
{
    sub_val=$1
    for sub_id in `/folk/vlm/commandline/vlmTool find  -s amazon.wrs.com -l all | grep "^Target ID"| awk -F": " '{print $2}'`
    do
        info_id=`/folk/vlm/commandline/vlmTool getAttr -s amazon.wrs.com -t $sub_id all | grep $sub_val`
    
        if [ -n "$info_id" ];then
            echo ">>>>>>>>>>>>>>>>>>>>>>>>>"
            echo $sub_id
            echo $info_id
            echo "<<<<<<<<<<<<<<<<<<<<<<<<<"
        fi
    done
}


usage()
{
    echo "
    Usage:
    $0 [r|u|on|off|g|f|search|cp] value
        r: reserve     :: e.g. $0 r 22409
        u: unreserve   :: e.g. $0 u 22409
        on: turnon     :: e.g. $0 on 22409
        off: turnoff   :: e.g. $0 off 22409
        g: getAttr     :: e.g. $0 g 22409
        f: findMine    :: e.g. $0 f -l
        search: find   :: e.g. $0 search t4240
        cp: upload     :: e.g. $0 cp 22609 [~/vlm]
        nb: advanced search :: e.g $0 nb jhu2
        reboot: reboot
    "
}

#pick up the related filed from $copy_path
got_copyfile()
{
    if [ ! -d "$copy_path" ]; then echo "Give me the correct path:-)";exit 1; fi 
    for fff in `ls $copy_path`
    do
        realfile=`readlink -f $copy_path/$fff`
        kkk_f=`echo $realfile | grep ".bin$" &> /dev/null;echo $?`
        ddd_f=`echo $realfile | grep ".dtb$" &> /dev/null;echo $?`
        rrr_f=`echo $realfile | grep ".tar.bz2$" &> /dev/null;echo $?`

        if [ $kkk_f -eq 0 ];then
           kkk=$realfile
           echo kernel: $realfile
        elif [ $ddd_f -eq 0 ];then
           ddd=$realfile
           echo dtb: $realfile
        elif [ $rrr_f -eq 0 ];then
           rrr=$realfile
           echo rootfs: $realfile
        fi
    done
}


#main
[ $# -gt 3 ] &&{ echo "Too many options...";usage;exit 1; }
[ -z $1 ] &&{ echo "please input action...";usage;exit 1; }

if [ x"$1" = x"f" ];then
    :
else
    [ -z $2 ] &&{ echo "please input barcode...";usage;exit 1; }
fi

case $1 in
    f) opt="findMine";;
    r) opt="reserve";;
    u) opt="unreserve";;
    on) opt="turnOn";;
    off) opt="turnOff";;
    g) opt="getAttr";;
    search) opt="find";;
    cp) opt="copyFile";got_copyfile;;
    reboot) opt="reboot";;
    nb) opt="nb";;
    *) echo "wrong options";;
esac


if [ $opt = "reserve" ]; then
    /folk/vlm/commandline/vlmTool reserve -s amazon.wrs.com -t $2
elif [ $opt = "nb" ];then
    nb $2 
elif [ $opt = "unreserve" ];then
    /folk/vlm/commandline/vlmTool unreserve -s amazon.wrs.com -t $2
elif [ $opt = "reboot" ];then
    /folk/vlm/commandline/vlmTool reboot -s amazon.wrs.com -t $2
elif [ $opt = "turnOn" ];then
    /folk/vlm/commandline/vlmTool turnOn -s amazon.wrs.com -t $2
elif [ $opt = "turnOff" ];then
    /folk/vlm/commandline/vlmTool turnOff -s amazon.wrs.com -t $2
elif [ $opt = "getAttr" ];then
    /folk/vlm/commandline/vlmTool getAttr -s amazon.wrs.com -t $2 all
elif [ $opt = "findMine" ];then
    /folk/vlm/commandline/vlmTool findMine -s amazon.wrs.com  ${2:+"-l"}
elif [ $opt = "find" ];then
    /folk/vlm/commandline/vlmTool find  -s amazon.wrs.com -l all | grep "$2" -a3
elif [ $opt = "copyFile" ];then
    if [ -z $ddd ];  then
        echo "/folk/vlm/commandline/vlmTool copyFile -s amazon.wrs.com -t $2  -k $kkk -r $rrr"
        sleep 5
        /folk/vlm/commandline/vlmTool copyFile -s amazon.wrs.com -t $2  -k $kkk  -r $rrr
    else
        echo "/folk/vlm/commandline/vlmTool copyFile -s amazon.wrs.com -t $2  -k $kkk -d $ddd -r $rrr"
        sleep 5
        /folk/vlm/commandline/vlmTool copyFile -s amazon.wrs.com -t $2  -k $kkk -d $ddd -r $rrr
    fi
fi

echo "Done"
